### ISSUE TITLE
How do I reproduce？

### ISSUE THREAD

**Issue by hcz-czh** [video2game/video2game#1]
How do I reproduce the garden sample with the pre-trained model

**Comment by xiahongchi** [comment]
Hi, sorry for late reply. You could try to follow our instructions in README, thanks!

**Comment by PandaZ0912** [comment]
> 嗨，很抱歉回复晚了。您可以尝试按照 README 中的说明进行作，谢谢！

Hello, I would like to ask what segmentation tool you used when reconstructing the garden scene? Thank you!
