### ISSUE TITLE
radial mesh artifacts in gardenvase

### ISSUE THREAD

**Issue by SuX97** [video2game/video2game#4]
Hi, thanks for your work!

I run the default config of the mip360 gardenvase case, but find the final extracted mesh having radial mesh artifacts like 
![snapshot_gardenvase](https://github.com/video2game/video2game/assets/25632694/416d9882-d5bc-40ac-8700-5130803f664c)
, which I do not observe in the online game demo. Instead, the online game demo seems to have a background image blocks with octango shape.
![image](https://github.com/video2game/video2game/assets/25632694/65f6903a-56d4-4ea2-aba0-be783d1dcbfe)

I am wondering if I missed something, or the game asset is manually fixed?

Looking forward to your reply!

**Comment by xiahongchi** [comment]
Hi, sorry for late reply. I haven't manually changed anything to the mesh. For radial effect, it's caused by contraction function. To avoid this, you could try no contraction.

**Comment by flyingGH** [comment]
@SuX97 @xiahongchi  I meet the nan problem in trainning gardenvase case, can you give me some advice?
Can I have your contact information? If it's convenient.
I make follwing modications for decrease memory consumption:
1/4 sampling for training data.
